In [1]:
import pandas as pd
import numpy as np

In [2]:
data_2010 = pd.read_csv('Resources/ghe2010csv.csv', header = 6)
data_2015 = pd.read_csv('Resources/ghe2015csv.csv', header = 6)
data_2019 = pd.read_csv('Resources/ghe2019csv.csv', header = 6)

data_2010.head()

,Sex,GHE code,Unnamed: 2,GHE cause,Unnamed: 4,Unnamed: 5,Member State\n(See Notes for explanation of colour codes),Afghanistan,Albania,Algeria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
0,NaN,NaN,NaN,NaN,NaN,NaN,ISO-3 Code,AFG,ALB,DZA,...,TZA,USA,URY,UZB,VUT,VEN,VNM,YEM,ZMB,ZWE
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,3,4,...,4,1,2,2,4,1,4,4,4,4
2,Persons,NaN,NaN,Population ('000) (2),NaN,NaN,NaN,"29,186","2,948","35,977",...,"44,347","309,011","3,359","28,516",236,"28,440","87,968","23,155","13,606","12,698"
3,Persons,0.0,NaN,All Causes,NaN,NaN,NaN,247.7,19.7,157.9,...,350.3,2470.5,32.6,171.1,1.8,138.4,620.8,124.5,127.1,161.5
4,Persons,10.0,I.,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,119.3,0.6,25.2,...,230.4,140.7,2.6,22.6,0.3,17.1,79.8,46.1,80.6,100.1

In [4]:
data_2015.head()

,Sex,GHE code,Unnamed: 2,GHE cause,Unnamed: 4,Unnamed: 5,Member State\n(See Notes for explanation of colour codes),Afghanistan,Albania,Algeria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
0,NaN,NaN,NaN,NaN,NaN,NaN,ISO-3 Code,AFG,ALB,DZA,...,TZA,USA,URY,UZB,VUT,VEN,VNM,YEM,ZMB,ZWE
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,3,4,...,4,1,2,2,4,1,4,4,4,4
2,Persons,NaN,NaN,Population ('000) (2),NaN,NaN,NaN,"34,414","2,891","39,728",...,"51,483","320,878","3,412","30,930",271,"30,082","92,677","26,498","15,879","13,815"
3,Persons,0.0,NaN,All Causes,NaN,NaN,NaN,252.4,23.1,181.8,...,321.0,2713.5,33.0,172.5,2.0,159.7,679.5,146.5,120.3,126.1
4,Persons,10.0,I.,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,99.4,0.7,26.8,...,190.7,153.3,2.4,18.1,0.4,20.7,73.1,47.0,70.1,64.6

In [5]:
data_2019.head()

,Sex,GHE code,Unnamed: 2,GHE cause,Unnamed: 4,Unnamed: 5,Member State\n(See Notes for explanation of colour codes),Afghanistan,Albania,Algeria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
0,NaN,NaN,NaN,NaN,NaN,NaN,ISO-3 Code,AFG,ALB,DZA,...,TZA,USA,URY,UZB,VUT,VEN,VNM,YEM,ZMB,ZWE
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,3,4,...,4,1,2,2,4,1,4,4,4,4
2,Persons,NaN,NaN,Population ('000) (2),NaN,NaN,NaN,"38,042","2,881","43,053",...,"58,005","329,065","3,462","32,982",300,"28,516","96,462","29,162","17,861","14,645"
3,Persons,0.0,NaN,All Causes,NaN,NaN,NaN,254.8,31.2,203.3,...,321.7,2949.2,34.8,170.3,2.1,172.1,727.9,170.0,121.1,117.7
4,Persons,10.0,I.,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,83.9,0.9,26.4,...,174.8,156.4,2.5,14.0,0.4,26.8,67.7,51.3,68.4,56.1

In [6]:
data_2010.columns

Index(['Sex', 'GHE code', 'Unnamed: 2', 'GHE cause', 'Unnamed: 4',
       'Unnamed: 5',
       'Member State\n(See Notes for explanation of colour codes)',
       'Afghanistan', 'Albania', 'Algeria',
       ...
       'United Republic of Tanzania', 'United States of America', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela (Bolivarian Republic of)',
       'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='object', length=190)

In [7]:
data_2015.columns

Index(['Sex', 'GHE code', 'Unnamed: 2', 'GHE cause', 'Unnamed: 4',
       'Unnamed: 5',
       'Member State\n(See Notes for explanation of colour codes)',
       'Afghanistan', 'Albania', 'Algeria',
       ...
       'United Republic of Tanzania', 'United States of America', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela (Bolivarian Republic of)',
       'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='object', length=190)

In [8]:
data_2019.columns

Index(['Sex', 'GHE code', 'Unnamed: 2', 'GHE cause', 'Unnamed: 4',
       'Unnamed: 5',
       'Member State\n(See Notes for explanation of colour codes)',
       'Afghanistan', 'Albania', 'Algeria',
       ...
       'United Republic of Tanzania', 'United States of America', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela (Bolivarian Republic of)',
       'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='object', length=190)

In [9]:
data_2010.columns = data_2010.columns.str.replace('Unnamed: 4', 'Cause Category').str.replace('Unnamed: 5', 'Disease/Injury').str.replace('Member State\n(See Notes for explanation of colour codes)', 'Condition')
data_2010

,Sex,GHE code,Unnamed: 2,GHE cause,Cause Category,Disease/Injury,Condition,Afghanistan,Albania,Algeria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
0,NaN,NaN,NaN,NaN,NaN,NaN,ISO-3 Code,AFG,ALB,DZA,...,TZA,USA,URY,UZB,VUT,VEN,VNM,YEM,ZMB,ZWE
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,3,4,...,4,1,2,2,4,1,4,4,4,4
2,Persons,NaN,NaN,Population ('000) (2),NaN,NaN,NaN,"29,186","2,948","35,977",...,"44,347","309,011","3,359","28,516",236,"28,440","87,968","23,155","13,606","12,698"
3,Persons,0.0,NaN,All Causes,NaN,NaN,NaN,247.7,19.7,157.9,...,350.3,2470.5,32.6,171.1,1.8,138.4,620.8,124.5,127.1,161.5
4,Persons,10.0,I.,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,119.3,0.6,25.2,...,230.4,140.7,2.6,22.6,0.3,17.1,79.8,46.1,80.6,100.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,Females,1590.0,NaN,NaN,8.0,Other unintentional injuries,NaN,1.8,0.0,0.4,...,1.9,8.7,0.3,0.4,0.0,0.5,1.4,0.7,0.7,0.9
617,Females,1600.0,NaN,B.,Intentional injuries,NaN,NaN,3.7,0.1,0.6,...,1.6,13.1,0.2,0.9,0.0,1.3,2.0,1.0,0.6,1.5
618,Females,1610.0,NaN,NaN,1.0,Self-harm,NaN,0.6,0.1,0.4,...,0.6,9.1,0.1,0.7,0.0,0.1,1.9,0.5,0.4,1.1
619,Females,1620.0,NaN,NaN,2.0,Interpersonal violence,NaN,0.4,0.0,0.1,...,1.0,3.8,0.0,0.2,0.0,1.2,0.2,0.3,0.3,0.4
620,Females,1630.0,NaN,NaN,3.0,Collective violence and legal intervention,NaN,2.8,0.0,0.1,...,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0

In [10]:
data_2015.columns = data_2015.columns.str.replace('Unnamed: 4', 'Cause Category').str.replace('Unnamed: 5', 'Disease/Injury').str.replace('Member State\n(See Notes for explanation of colour codes)', 'Condition')
data_2015

,Sex,GHE code,Unnamed: 2,GHE cause,Cause Category,Disease/Injury,Condition,Afghanistan,Albania,Algeria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
0,NaN,NaN,NaN,NaN,NaN,NaN,ISO-3 Code,AFG,ALB,DZA,...,TZA,USA,URY,UZB,VUT,VEN,VNM,YEM,ZMB,ZWE
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,3,4,...,4,1,2,2,4,1,4,4,4,4
2,Persons,NaN,NaN,Population ('000) (2),NaN,NaN,NaN,"34,414","2,891","39,728",...,"51,483","320,878","3,412","30,930",271,"30,082","92,677","26,498","15,879","13,815"
3,Persons,0.0,NaN,All Causes,NaN,NaN,NaN,252.4,23.1,181.8,...,321.0,2713.5,33.0,172.5,2.0,159.7,679.5,146.5,120.3,126.1
4,Persons,10.0,I.,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,99.4,0.7,26.8,...,190.7,153.3,2.4,18.1,0.4,20.7,73.1,47.0,70.1,64.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,Females,1590.0,NaN,NaN,8.0,Other unintentional injuries,NaN,1.2,0.0,0.5,...,1.8,9.4,0.4,0.4,0.0,0.5,1.7,1.0,0.7,0.8
617,Females,1600.0,NaN,B.,Intentional injuries,NaN,NaN,8.7,0.1,0.6,...,1.5,14.8,0.2,1.0,0.0,1.4,2.3,3.4,0.6,1.4
618,Females,1610.0,NaN,NaN,1.0,Self-harm,NaN,0.6,0.0,0.4,...,0.5,11.0,0.1,0.9,0.0,0.1,2.1,0.6,0.3,0.9
619,Females,1620.0,NaN,NaN,2.0,Interpersonal violence,NaN,0.6,0.0,0.2,...,1.0,3.7,0.0,0.1,0.0,1.2,0.2,0.6,0.3,0.4
620,Females,1630.0,NaN,NaN,3.0,Collective violence and legal intervention,NaN,7.6,0.0,0.0,...,0.0,0.1,0.0,0.0,0.0,0.0,0.0,2.2,0.0,0.0

In [11]:
data_2019.columns = data_2019.columns.str.replace('Unnamed: 4', 'Cause Category').str.replace('Unnamed: 5', 'Disease/Injury').str.replace('Member State\n(See Notes for explanation of colour codes)', 'Condition')
data_2019

,Sex,GHE code,Unnamed: 2,GHE cause,Cause Category,Disease/Injury,Condition,Afghanistan,Albania,Algeria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
0,NaN,NaN,NaN,NaN,NaN,NaN,ISO-3 Code,AFG,ALB,DZA,...,TZA,USA,URY,UZB,VUT,VEN,VNM,YEM,ZMB,ZWE
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,3,4,...,4,1,2,2,4,1,4,4,4,4
2,Persons,NaN,NaN,Population ('000) (2),NaN,NaN,NaN,"38,042","2,881","43,053",...,"58,005","329,065","3,462","32,982",300,"28,516","96,462","29,162","17,861","14,645"
3,Persons,0.0,NaN,All Causes,NaN,NaN,NaN,254.8,31.2,203.3,...,321.7,2949.2,34.8,170.3,2.1,172.1,727.9,170.0,121.1,117.7
4,Persons,10.0,I.,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,83.9,0.9,26.4,...,174.8,156.4,2.5,14.0,0.4,26.8,67.7,51.3,68.4,56.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,Females,1590.0,NaN,NaN,8.0,Other unintentional injuries,NaN,1.2,0.0,0.5,...,1.8,11.0,0.4,0.4,0.0,0.6,1.9,0.8,0.6,0.7
617,Females,1600.0,NaN,B.,Intentional injuries,NaN,NaN,14.1,0.1,0.6,...,1.7,16.2,0.2,0.9,0.0,1.4,2.5,5.3,0.5,1.1
618,Females,1610.0,NaN,NaN,1.0,Self-harm,NaN,0.7,0.0,0.4,...,0.6,12.4,0.2,0.8,0.0,0.1,2.2,0.7,0.2,0.7
619,Females,1620.0,NaN,NaN,2.0,Interpersonal violence,NaN,0.6,0.0,0.2,...,1.1,3.7,0.1,0.1,0.0,1.3,0.2,0.7,0.3,0.4
620,Females,1630.0,NaN,NaN,3.0,Collective violence and legal intervention,NaN,12.8,0.0,0.0,...,0.0,0.1,0.0,0.0,0.0,0.0,0.0,3.9,0.0,0.0

In [12]:
data_2010 = data_2010[['Sex', 'GHE cause', 'Cause Category',
       'Disease/Injury',
       'Condition', 'Germany', 'Netherlands','Switzerland','United Kingdom', 'United States of America',]]
data_2010

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
0,NaN,NaN,NaN,NaN,ISO-3 Code,DEU,NLD,CHE,GBR,USA
1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1
2,Persons,Population ('000) (2),NaN,NaN,NaN,"80,827","16,683","7,809","63,460","309,011"
3,Persons,All Causes,NaN,NaN,NaN,836.9,135.3,62.0,568.3,2470.5
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,38.8,8.6,2.3,41.6,140.7
...,...,...,...,...,...,...,...,...,...,...
616,Females,NaN,8.0,Other unintentional injuries,NaN,2.9,0.8,0.1,2.5,8.7
617,Females,B.,Intentional injuries,NaN,NaN,3.0,0.5,0.4,1.6,13.1
618,Females,NaN,1.0,Self-harm,NaN,2.8,0.5,0.4,1.2,9.1
619,Females,NaN,2.0,Interpersonal violence,NaN,0.2,0.1,0.0,0.4,3.8
620,Females,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.0,0.2

In [13]:
data_2015 = data_2015[['Sex', 'GHE cause', 'Cause Category',
       'Disease/Injury',
       'Condition', 'Germany', 'Netherlands','Switzerland','United Kingdom', 'United States of America',]]
data_2015

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
0,NaN,NaN,NaN,NaN,ISO-3 Code,DEU,NLD,CHE,GBR,USA
1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1
2,Persons,Population ('000) (2),NaN,NaN,NaN,"81,787","16,938","8,297","65,860","320,878"
3,Persons,All Causes,NaN,NaN,NaN,928.9,146.2,67.8,619.2,2713.5
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,46.5,8.5,3.1,49.9,153.3
...,...,...,...,...,...,...,...,...,...,...
616,Females,NaN,8.0,Other unintentional injuries,NaN,3.4,0.8,0.2,2.4,9.4
617,Females,B.,Intentional injuries,NaN,NaN,3.4,0.7,0.4,1.8,14.8
618,Females,NaN,1.0,Self-harm,NaN,3.0,0.7,0.4,1.5,11.0
619,Females,NaN,2.0,Interpersonal violence,NaN,0.4,0.0,0.0,0.3,3.7
620,Females,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.0,0.1

In [14]:
data_2019 = data_2019[['Sex', 'GHE cause', 'Cause Category',
       'Disease/Injury',
       'Condition', 'Germany', 'Netherlands','Switzerland','United Kingdom', 'United States of America',]]
data_2019

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
0,NaN,NaN,NaN,NaN,ISO-3 Code,DEU,NLD,CHE,GBR,USA
1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1
2,Persons,Population ('000) (2),NaN,NaN,NaN,"83,517","17,097","8,591","67,530","329,065"
3,Persons,All Causes,NaN,NaN,NaN,845.4,153.1,69.1,614.5,2949.2
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,40.2,9.2,3.3,50.1,156.4
...,...,...,...,...,...,...,...,...,...,...
616,Females,NaN,8.0,Other unintentional injuries,NaN,3.5,1.0,0.2,2.6,11.0
617,Females,B.,Intentional injuries,NaN,NaN,3.0,0.8,0.4,1.7,16.2
618,Females,NaN,1.0,Self-harm,NaN,2.6,0.7,0.4,1.4,12.4
619,Females,NaN,2.0,Interpersonal violence,NaN,0.4,0.0,0.0,0.3,3.7
620,Females,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.0,0.1

In [15]:
data_2010['Sex'].unique()

array([nan, 'Persons', 'Males', 'Females'], dtype=object)

In [16]:
data_2015['Sex'].unique()

array([nan, 'Persons', 'Males', 'Females'], dtype=object)

In [17]:
data_2019['Sex'].unique()

array([nan, 'Persons', 'Males', 'Females'], dtype=object)

In [18]:
data_2010.loc[data_2010['Sex']=='Persons']

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
2,Persons,Population ('000) (2),NaN,NaN,NaN,"80,827","16,683","7,809","63,460","309,011"
3,Persons,All Causes,NaN,NaN,NaN,836.9,135.3,62.0,568.3,2470.5
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,38.8,8.6,2.3,41.6,140.7
5,Persons,A.,Infectious and parasitic diseases,NaN,NaN,15.8,2.3,0.8,6.5,69.8
6,Persons,NaN,1.0,Tuberculosis,NaN,0.4,0.1,0.0,0.4,0.6
...,...,...,...,...,...,...,...,...,...,...
202,Persons,NaN,8.0,Other unintentional injuries,NaN,5.7,1.4,0.4,4.6,20.6
203,Persons,B.,Intentional injuries,NaN,NaN,11.5,1.8,1.2,6.1,59.0
204,Persons,NaN,1.0,Self-harm,NaN,10.7,1.6,1.1,5.0,40.5
205,Persons,NaN,2.0,Interpersonal violence,NaN,0.8,0.2,0.1,1.0,16.9
206,Persons,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.1,1.6

In [19]:
data_2015.loc[data_2015['Sex']=='Persons']

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
2,Persons,Population ('000) (2),NaN,NaN,NaN,"81,787","16,938","8,297","65,860","320,878"
3,Persons,All Causes,NaN,NaN,NaN,928.9,146.2,67.8,619.2,2713.5
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,46.5,8.5,3.1,49.9,153.3
5,Persons,A.,Infectious and parasitic diseases,NaN,NaN,21.0,3.7,0.9,7.5,73.7
6,Persons,NaN,1.0,Tuberculosis,NaN,0.3,0.0,0.0,0.4,0.5
...,...,...,...,...,...,...,...,...,...,...
202,Persons,NaN,8.0,Other unintentional injuries,NaN,7.0,1.4,0.4,4.7,22.4
203,Persons,B.,Intentional injuries,NaN,NaN,11.6,2.1,1.3,6.7,65.8
204,Persons,NaN,1.0,Self-harm,NaN,10.9,2.0,1.2,5.8,46.2
205,Persons,NaN,2.0,Interpersonal violence,NaN,0.8,0.1,0.1,0.9,18.4
206,Persons,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.0,1.3

In [20]:
data_2019.loc[data_2019['Sex']=='Persons']

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
2,Persons,Population ('000) (2),NaN,NaN,NaN,"83,517","17,097","8,591","67,530","329,065"
3,Persons,All Causes,NaN,NaN,NaN,845.4,153.1,69.1,614.5,2949.2
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,40.2,9.2,3.3,50.1,156.4
5,Persons,A.,Infectious and parasitic diseases,NaN,NaN,16.2,3.5,1.0,7.4,73.4
6,Persons,NaN,1.0,Tuberculosis,NaN,0.3,0.0,0.0,0.4,0.5
...,...,...,...,...,...,...,...,...,...,...
202,Persons,NaN,8.0,Other unintentional injuries,NaN,8.2,1.6,0.4,5.5,26.0
203,Persons,B.,Intentional injuries,NaN,NaN,11.1,2.1,1.3,6.2,73.3
204,Persons,NaN,1.0,Self-harm,NaN,10.3,2.0,1.2,5.3,53.1
205,Persons,NaN,2.0,Interpersonal violence,NaN,0.8,0.1,0.0,0.9,19.0
206,Persons,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.0,1.2

In [21]:
data_2010_summary = data_2010.loc[data_2010['Sex']=='Persons']
data_2010_summary

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
2,Persons,Population ('000) (2),NaN,NaN,NaN,"80,827","16,683","7,809","63,460","309,011"
3,Persons,All Causes,NaN,NaN,NaN,836.9,135.3,62.0,568.3,2470.5
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,38.8,8.6,2.3,41.6,140.7
5,Persons,A.,Infectious and parasitic diseases,NaN,NaN,15.8,2.3,0.8,6.5,69.8
6,Persons,NaN,1.0,Tuberculosis,NaN,0.4,0.1,0.0,0.4,0.6
...,...,...,...,...,...,...,...,...,...,...
202,Persons,NaN,8.0,Other unintentional injuries,NaN,5.7,1.4,0.4,4.6,20.6
203,Persons,B.,Intentional injuries,NaN,NaN,11.5,1.8,1.2,6.1,59.0
204,Persons,NaN,1.0,Self-harm,NaN,10.7,1.6,1.1,5.0,40.5
205,Persons,NaN,2.0,Interpersonal violence,NaN,0.8,0.2,0.1,1.0,16.9
206,Persons,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.1,1.6

In [22]:
data_2015_summary = data_2015.loc[data_2015['Sex']=='Persons']
data_2015_summary

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
2,Persons,Population ('000) (2),NaN,NaN,NaN,"81,787","16,938","8,297","65,860","320,878"
3,Persons,All Causes,NaN,NaN,NaN,928.9,146.2,67.8,619.2,2713.5
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,46.5,8.5,3.1,49.9,153.3
5,Persons,A.,Infectious and parasitic diseases,NaN,NaN,21.0,3.7,0.9,7.5,73.7
6,Persons,NaN,1.0,Tuberculosis,NaN,0.3,0.0,0.0,0.4,0.5
...,...,...,...,...,...,...,...,...,...,...
202,Persons,NaN,8.0,Other unintentional injuries,NaN,7.0,1.4,0.4,4.7,22.4
203,Persons,B.,Intentional injuries,NaN,NaN,11.6,2.1,1.3,6.7,65.8
204,Persons,NaN,1.0,Self-harm,NaN,10.9,2.0,1.2,5.8,46.2
205,Persons,NaN,2.0,Interpersonal violence,NaN,0.8,0.1,0.1,0.9,18.4
206,Persons,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.0,1.3

In [23]:
data_2019_summary = data_2019.loc[data_2019['Sex']=='Persons']
data_2019_summary

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
2,Persons,Population ('000) (2),NaN,NaN,NaN,"83,517","17,097","8,591","67,530","329,065"
3,Persons,All Causes,NaN,NaN,NaN,845.4,153.1,69.1,614.5,2949.2
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,40.2,9.2,3.3,50.1,156.4
5,Persons,A.,Infectious and parasitic diseases,NaN,NaN,16.2,3.5,1.0,7.4,73.4
6,Persons,NaN,1.0,Tuberculosis,NaN,0.3,0.0,0.0,0.4,0.5
...,...,...,...,...,...,...,...,...,...,...
202,Persons,NaN,8.0,Other unintentional injuries,NaN,8.2,1.6,0.4,5.5,26.0
203,Persons,B.,Intentional injuries,NaN,NaN,11.1,2.1,1.3,6.2,73.3
204,Persons,NaN,1.0,Self-harm,NaN,10.3,2.0,1.2,5.3,53.1
205,Persons,NaN,2.0,Interpersonal violence,NaN,0.8,0.1,0.0,0.9,19.0
206,Persons,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.0,1.2

In [24]:
data_2010_summary.dtypes

Sex                         object
GHE cause                   object
Cause Category              object
Disease/Injury              object
Condition                   object
Germany                     object
Netherlands                 object
Switzerland                 object
United Kingdom              object
United States of America    object
dtype: object

In [25]:
data_2015_summary.dtypes

Sex                         object
GHE cause                   object
Cause Category              object
Disease/Injury              object
Condition                   object
Germany                     object
Netherlands                 object
Switzerland                 object
United Kingdom              object
United States of America    object
dtype: object

In [52]:
data_2015_copy = data_2015_summary.copy()

data_2015_copy[columns_to_convert] = data_2015_copy[columns_to_convert].apply(pd.to_numeric, errors='coerce')
data_2015_copy.dtypes

Sex                          object
GHE cause                    object
Cause Category               object
Disease/Injury               object
Condition                    object
Germany                     float64
Netherlands                 float64
Switzerland                 float64
United Kingdom              float64
United States of America    float64
dtype: object

In [54]:
data_2019_copy = data_2019_summary.copy()

# Convert specified columns to float 
#data_2019_copy.loc[:, columns_to_convert] = data_2019_copy[columns_to_convert].apply(pd.to_numeric, errors='coerce')
data_2019_copy[columns_to_convert] = data_2019_copy[columns_to_convert].apply(pd.to_numeric, errors='coerce')
data_2019_copy.dtypes
#data_2019_copy.head()

Sex                          object
GHE cause                    object
Cause Category               object
Disease/Injury               object
Condition                    object
Germany                     float64
Netherlands                 float64
Switzerland                 float64
United Kingdom              float64
United States of America    float64
dtype: object

In [28]:
data_2019_copy.dtypes

Sex                          object
GHE cause                    object
Cause Category               object
Disease/Injury               object
Condition                    object
Germany                     float64
Netherlands                 float64
Switzerland                 float64
United Kingdom              float64
United States of America    float64
dtype: object

In [56]:
data_2010_copy = data_2010_summary.copy()

data_2010_copy[columns_to_convert] = data_2010_copy[columns_to_convert].apply(pd.to_numeric, errors='coerce')
data_2010_copy.dtypes

Sex                          object
GHE cause                    object
Cause Category               object
Disease/Injury               object
Condition                    object
Germany                     float64
Netherlands                 float64
Switzerland                 float64
United Kingdom              float64
United States of America    float64
dtype: object

In [30]:
data_2010_copy.head(20)

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
2,Persons,Population ('000) (2),NaN,NaN,NaN,"80,827","16,683","7,809","63,460","309,011"
3,Persons,All Causes,NaN,NaN,NaN,836.9,135.3,62.0,568.3,2470.5
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,38.8,8.6,2.3,41.6,140.7
5,Persons,A.,Infectious and parasitic diseases,NaN,NaN,15.8,2.3,0.8,6.5,69.8
6,Persons,NaN,1.0,Tuberculosis,NaN,0.4,0.1,0.0,0.4,0.6
7,Persons,NaN,2.0,STDs excluding HIV,NaN,0.0,0.0,0.0,0.1,0.2
8,Persons,NaN,NaN,a.,Syphilis,0.0,0.0,0.0,0.0,0.0
9,Persons,NaN,NaN,b.,Chlamydia,.,.,.,.,.
10,Persons,NaN,NaN,c.,Gonorrhoea,.,.,.,.,0.0
11,Persons,NaN,NaN,d.,Trichomoniasis,.,.,.,.,.
12,Persons,NaN,NaN,e.,Genital herpes,.,.,.,.,.
13,Persons,NaN,NaN,f.,Other STDs,0.0,0.0,0.0,0.1,0.1
14,Persons,NaN,3.0,HIV/AIDS,NaN,0.5,0.1,0.0,0.3,8.5
15,Persons,NaN,4.0,Diarrhoeal diseases,NaN,2.9,0.2,0.1,1.4,10.7
16,Persons,NaN,5.0,Childhood-cluster diseases,NaN,0.0,0.0,0.0,0.0,0.0
17,Persons,NaN,NaN,a.,Whooping cough,0.0,0.0,0.0,0.0,0.0
18,Persons,NaN,NaN,b.,Diphtheria,0.0,0.0,0.0,0.0,0.0
19,Persons,NaN,NaN,c.,Measles,0.0,.,.,.,0.0
20,Persons,NaN,NaN,d.,Tetanus,0.0,.,0.0,0.0,0.0
21,Persons,NaN,6.0,Meningitis,NaN,0.2,0.1,0.0,0.3,0.8

In [62]:
dropped_2010=data_2010_copy.drop(columns=['GHE cause', 'Cause Category', 'Sex', 'Disease/Injury'])
#dropped_2010.dtypes
dropped_2010_data = dropped_2010.dropna(subset=['Condition'])

sorted_2010=dropped_2010_data.sort_values(by='Germany', ascending= False)
sorted_2010.head(20)
#sorted_2010.dtypes

,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
145,Ischaemic stroke,44.8,6.1,2.8,35.4,77.1
146,Haemorrhagic stroke,18.5,3.3,1.3,16.0,58.7
171,Other chronic kidney disease,15.5,1.8,0.6,4.5,53.7
158,Cirrhosis due to alcohol use,7.4,0.4,0.3,4.3,9.2
99,Non-Hodgkin lymphoma,6.7,1.3,0.5,5.2,22.8
170,Chronic kidney disease due to diabetes,6.6,0.4,0.3,1.0,18.7
100,Multiple myeloma,4.4,0.8,0.4,3.2,12.8
159,Other liver cirrhosis,3.8,0.2,0.2,2.1,7.5
77,Liver cancer secondary to alcohol use,3.6,0.3,0.3,1.4,5.8
82,Malignant skin melanoma,3.0,0.9,0.3,2.5,10.2
70,Other pharynx,2.9,0.3,0.2,1.0,3.8
68,Lip and oral cavity,2.6,0.4,0.2,1.5,4.8
157,Cirrhosis due to hepatitis C,2.4,0.1,0.1,0.6,14.5
76,Liver cancer secondary to hepatitis C,2.2,0.2,0.2,1.5,8.3
156,Cirrhosis due to hepatitis B,1.2,0.1,0.1,0.7,1.0
78,Other liver cancer,1.0,0.1,0.1,0.5,3.9
122,Other drug use disorders,1.0,0.1,0.1,1.0,9.3
83,Non-melanoma skin cancer,0.7,0.1,0.1,0.6,3.3
26,Acute hepatitis C,0.7,0.0,0.0,0.2,6.9
75,Liver cancer secondary to hepatitis B,0.7,0.1,0.1,0.5,2.5

In [26]:
# data_2010_summary.iloc[2:, 6:11] = data_2010_summary.iloc[2:, 6:11].replace('', np.nan).astype(float)

In [27]:
# # Replace non-numeric values with NaN in data_2010_summary
# data_2010_summary.iloc[2:, 6:11] = data_2010_summary.iloc[2:, 6:11].replace('.', np.nan) 

# # Convert columns to float in data_2010_summary  
# data_2010_summary.iloc[2:, 6:11] = data_2010_summary.iloc[2:, 6:11].astype(float)

# # Print updated data_2010_summary
# print(data_2010_summary)

In [ ]:
# data_2010_summary_copy = data_2010_summary.copy()
# data_2010_summary_copy.iloc[2:, 6:11] = data_2010_summary_copy.iloc[2:, 6:11].replace('.', np.nan).astype(float)

In [24]:
data_2010_summary.iloc[3:, 5:] = data_2010_summary.iloc[3:, 5:].apply(pd.to_numeric, errors='coerce')

data_2019_summary

C:\Users\hyeco\AppData\Local\Temp\ipykernel_18608\1504335379.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_2010_summary.iloc[3:, 5:] = data_2010_summary.iloc[3:, 5:].apply(pd.to_numeric, errors='coerce')

,Sex,GHE cause,Cause Category,Disease/Injury,Condition,Germany,Netherlands,Switzerland,United Kingdom,United States of America
2,Persons,Population ('000) (2),NaN,NaN,NaN,"83,517","17,097","8,591","67,530","329,065"
3,Persons,All Causes,NaN,NaN,NaN,845.4,153.1,69.1,614.5,2949.2
4,Persons,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN,40.2,9.2,3.3,50.1,156.4
5,Persons,A.,Infectious and parasitic diseases,NaN,NaN,16.2,3.5,1.0,7.4,73.4
6,Persons,NaN,1.0,Tuberculosis,NaN,0.3,0.0,0.0,0.4,0.5
...,...,...,...,...,...,...,...,...,...,...
202,Persons,NaN,8.0,Other unintentional injuries,NaN,8.2,1.6,0.4,5.5,26.0
203,Persons,B.,Intentional injuries,NaN,NaN,11.1,2.1,1.3,6.2,73.3
204,Persons,NaN,1.0,Self-harm,NaN,10.3,2.0,1.2,5.3,53.1
205,Persons,NaN,2.0,Interpersonal violence,NaN,0.8,0.1,0.0,0.9,19.0
206,Persons,NaN,3.0,Collective violence and legal intervention,NaN,0.0,0.0,0.0,0.0,1.2

In [25]:
data_2010_summary.dtypes

Sex                         object
GHE cause                   object
Cause Category              object
Disease/Injury              object
Condition                   object
Germany                     object
Netherlands                 object
Switzerland                 object
United Kingdom              object
United States of America    object
dtype: object

In [ ]:

top_values_2010 = changehere.iloc[6:11, 2:6].apply(lambda x: x.nlargest(12), axis=1)

In [ ]:
for country, values in top_values_2010.iteritems():
    print("Country:", country)
    print(values)
    print()